var skill_skill_cfg =
[
	{
		id : 1,
		item_id : "i011",
		name : "skill_name_1",
		description : "skill_desc_1",
		pos : 1,
		skill_icon : "skill_02",
		skill_sound : "skill_1",
		skill_duration : 5,
		skill_range : 0,
		cost : 5,
		ratio : 1,
		hitrate : 1,
		skill_immune : [5],
		skill_unlock : 0,
		summon_type : 0,
	},
	{
		id : 2,
		item_id : "i012",
		name : "skill_name_2",
		description : "skill_desc_2",
		pos : 0,
		skill_icon : "skill_01",
		skill_sound : "skill_2",
		skill_duration : 10,
		skill_range : 0,
		cost : 5,
		ratio : 1,
		hitrate : 1,
		skill_immune : [],
		skill_unlock : 0,
		summon_type : 0,
	},
	{
		id : 3,
		item_id : "i013",
		name : "skill_name_3",
		description : "skill_desc_3",
		pos : 2,
		skill_icon : "skill_04",
		skill_sound : "skill_3",
		skill_duration : 1,
		skill_range : 0,
		cost : 5,
		ratio : 1,
		hitrate : 1,
		skill_immune : [],
		skill_unlock : 0,
		summon_type : ["hujing_jj_zh","dapanyu_jj_zh","moguiyu_jj_zh","haigui_jj_zh","suolianyu_jj_zh","cheqiyu_jj_zh","haitun_jj_zh","sanshengyu_jj_zh","shuimu_jj_zh","shuangshengyu_jj_zh"],
	},
	{
		id : 4,
		item_id : "i014",
		name : "skill_name_4",
		description : "skill_desc_4",
		pos : -1,
		skill_icon : "skill_05",
		skill_sound : "skill_4",
		skill_duration : 1,
		skill_range : 0,
		cost : 0,
		ratio : 1,
		hitrate : 90,
		skill_immune : [2],
		skill_unlock : 0,
		summon_type : 0,
	},
	{
		id : 8,
		item_id : "i015",
		name : "skill_name_8",
		description : "skill_desc_8",
		pos : 5,
		skill_icon : "hedan1",
		skill_sound : "skill_8",
		skill_duration : 2,
		skill_range : 200,
		cost : 50,
		ratio : 400,
		hitrate : 115,
		skill_immune : [2],
		skill_unlock : 0,
		summon_type : 0,
	},
	{
		id : 9,
		item_id : "i016",
		name : "skill_name_9",
		description : "skill_desc_9",
		pos : 4,
		skill_icon : "hedan2",
		skill_sound : "skill_8",
		skill_duration : 2,
		skill_range : 250,
		cost : 150,
		ratio : 1000,
		hitrate : 135,
		skill_immune : [2],
		skill_unlock : 0,
		summon_type : 0,
	},
	{
		id : 10,
		item_id : "i017",
		name : "skill_name_10",
		description : "skill_desc_10",
		pos : 3,
		skill_icon : "hedan3",
		skill_sound : "skill_8",
		skill_duration : 2,
		skill_range : 300,
		cost : 500,
		ratio : 2500,
		hitrate : 180,
		skill_immune : [2],
		skill_unlock : 0,
		summon_type : 0,
	},
];
module.exports = skill_skill_cfg;