var aquarium_petfish_cfg =
[
	{
		id : 1,
		pic : "shuijingyumove_01",
		camp : 1,
		fishid : "shuijingyu_10",
		scale : 1.1,
		protime : 1800,
		probase : 1,
		chip : "i601",
		name : "fish_name_sjy",
		description : "fish_desc_sjy",
		treasureid : 101,
	},
	{
		id : 2,
		pic : "dabaishamove_01",
		camp : 4,
		fishid : "dabaisha_10",
		scale : 0.5,
		protime : 21600,
		probase : 1,
		chip : "i602",
		name : "fish_name_dbs",
		description : "fish_desc_dbs",
		treasureid : 105,
	},
	{
		id : 3,
		pic : "xiaochouyumove_01",
		camp : 1,
		fishid : "xiaochouyu_huang_10",
		scale : 1.3,
		protime : 1800,
		probase : 1,
		chip : "i603",
		name : "fish_name_xcy",
		description : "fish_desc_xcy",
		treasureid : 101,
	},
	{
		id : 4,
		pic : "hujingmove_01",
		camp : 4,
		fishid : "hujing_10",
		scale : 0.4,
		protime : 21600,
		probase : 1,
		chip : "i604",
		name : "fish_name_hj",
		description : "fish_desc_hj",
		treasureid : 105,
	},
	{
		id : 5,
		pic : "hetunmove_01",
		camp : 2,
		fishid : "hetun_huang_10",
		scale : 1.3,
		protime : 3600,
		probase : 1,
		chip : "i605",
		name : "fish_name_het",
		description : "fish_desc_het",
		treasureid : 102,
	},
	{
		id : 7,
		pic : "jiaodiemove_01",
		camp : 2,
		fishid : "jiaodie_huang_10",
		scale : 1.3,
		protime : 3600,
		probase : 1,
		chip : "i607",
		name : "fish_name_jd",
		description : "fish_desc_jd",
		treasureid : 102,
	},
	{
		id : 8,
		pic : "moguiyumove_01",
		camp : 4,
		fishid : "moguiyu_lan_10",
		scale : 0.5,
		protime : 21600,
		probase : 1,
		chip : "i608",
		name : "fish_name_mgy",
		description : "fish_desc_mgy",
		treasureid : 105,
	},
	{
		id : 9,
		pic : "chuitoushamove_01",
		camp : 4,
		fishid : "chuitousha_10",
		scale : 0.4,
		protime : 21600,
		probase : 1,
		chip : "i609",
		name : "fish_name_cts",
		description : "fish_desc_cts",
		treasureid : 105,
	},
	{
		id : 10,
		pic : "caomeiyumove_01",
		camp : 1,
		fishid : "caomeiyu_10",
		scale : 2,
		protime : 1800,
		probase : 1,
		chip : "i610",
		name : "fish_name_cmy",
		description : "fish_desc_cmy",
		treasureid : 101,
	},
	{
		id : 11,
		pic : "shuimumove_01",
		camp : 4,
		fishid : "shuimu_10",
		scale : 0.8,
		protime : 10800,
		probase : 1,
		chip : "i611",
		name : "fish_name_sm",
		description : "fish_desc_sm",
		treasureid : 104,
	},
	{
		id : 12,
		pic : "haiguimove_01",
		camp : 3,
		fishid : "haigui_10",
		scale : 0.9,
		protime : 7200,
		probase : 1,
		chip : "i612",
		name : "fish_name_hg",
		description : "fish_desc_hg",
		treasureid : 103,
	},
	{
		id : 13,
		pic : "lanbaoshiyumove_01",
		camp : 2,
		fishid : "baoshiyu_lan_10",
		scale : 1.1,
		protime : 3600,
		probase : 1,
		chip : "i613",
		name : "fish_name_bsy",
		description : "fish_desc_bsy",
		treasureid : 102,
	},
	{
		id : 14,
		pic : "duanhuibiyumove_01",
		camp : 2,
		fishid : "duanhuibiyu_huang_10",
		scale : 1.4,
		protime : 3600,
		probase : 1,
		chip : "i614",
		name : "fish_name_dhby",
		description : "fish_desc_dhby",
		treasureid : 102,
	},
	{
		id : 15,
		pic : "baofangfumove_01",
		camp : 4,
		fishid : "baofangfu_lan_10",
		scale : 0.8,
		protime : 10800,
		probase : 1,
		chip : "i615",
		name : "fish_name_bff",
		description : "fish_desc_bff",
		treasureid : 104,
	},
	{
		id : 16,
		pic : "jinqiangyumove_01",
		camp : 1,
		fishid : "jinqiangyu_10",
		scale : 1.6,
		protime : 1800,
		probase : 1,
		chip : "i616",
		name : "fish_name_jqy",
		description : "fish_desc_jqy",
		treasureid : 101,
	},
	{
		id : 17,
		pic : "yinlongyumove_01",
		camp : 2,
		fishid : "dianman_10",
		scale : 0.4,
		protime : 3600,
		probase : 1,
		chip : "i617",
		name : "fish_name_dm",
		description : "fish_desc_dm",
		treasureid : 102,
	},
	{
		id : 18,
		pic : "haitunmove_01",
		camp : 4,
		fishid : "haitun_10",
		scale : 0.7,
		protime : 10800,
		probase : 1,
		chip : "i618",
		name : "fish_name_ht",
		description : "fish_desc_ht",
		treasureid : 104,
	},
	{
		id : 20,
		pic : "jinsehaiguimove_01",
		camp : 4,
		fishid : "haigui_jj_10",
		scale : 0.4,
		protime : 21600,
		probase : 1,
		chip : "i620",
		name : "fish_name_jjhg",
		description : "fish_desc_jjhg",
		treasureid : 105,
	},
	{
		id : 21,
		pic : "bossbaozhayumove_01",
		camp : 4,
		fishid : "denglongyu_boss_10",
		scale : 0.25,
		protime : 43200,
		probase : 1,
		chip : "i621",
		name : "fish_name_dly",
		description : "fish_desc_dly",
		treasureid : 106,
	},
	{
		id : 22,
		pic : "mingyunyu03",
		camp : 4,
		fishid : "meirenyu_boss_10",
		scale : 0.3,
		protime : 43200,
		probase : 1,
		chip : "i622",
		name : "fish_name_mry",
		description : "fish_desc_mry",
		treasureid : 106,
	},
	{
		id : 23,
		pic : "lansedinianyumove_01",
		camp : 3,
		fishid : "dinianyu_lan_10",
		scale : 0.9,
		protime : 7200,
		probase : 1,
		chip : "i623",
		name : "fish_name_dny",
		description : "fish_desc_dny",
		treasureid : 103,
	},
	{
		id : 24,
		pic : "pipashuyumove_01",
		camp : 4,
		fishid : "pipashuyu_10",
		scale : 0.7,
		protime : 10800,
		probase : 1,
		chip : "i624",
		name : "fish_name_ppsy",
		description : "fish_desc_ppsy",
		treasureid : 104,
	},
	{
		id : 26,
		pic : "diaoyumove_01",
		camp : 3,
		fishid : "diaoyu_10",
		scale : 1,
		protime : 7200,
		probase : 1,
		chip : "i626",
		name : "fish_name_dy",
		description : "fish_desc_dy",
		treasureid : 103,
	},
	{
		id : 32,
		pic : "cheqiyumove_01",
		camp : 1,
		fishid : "cheqiyu_10",
		scale : 1.3,
		protime : 1800,
		probase : 1,
		chip : "i632",
		name : "fish_name_cqy",
		description : "fish_desc_cqy",
		treasureid : 101,
	},
	{
		id : 39,
		pic : "jianyumove_01",
		camp : 3,
		fishid : "jianyu_10",
		scale : 1.1,
		protime : 7200,
		probase : 1,
		chip : "i639",
		name : "fish_name_jy",
		description : "fish_desc_jy",
		treasureid : 103,
	},
	{
		id : 49,
		pic : "bosszhangyumove_01",
		camp : 4,
		fishid : "zhangyu_boss_10",
		scale : 0.4,
		protime : 43200,
		probase : 1,
		chip : "i649",
		name : "fish_name_zy",
		description : "fish_desc_zy",
		treasureid : 106,
	},
	{
		id : 51,
		pic : "bosssjlgmove_01",
		camp : 4,
		fishid : "longgui_boss_10",
		scale : 0.4,
		protime : 43200,
		probase : 1,
		chip : "i651",
		name : "fish_name_lg",
		description : "fish_desc_lg",
		treasureid : 106,
	},
	{
		id : 57,
		pic : "bosshaimamove_01",
		camp : 4,
		fishid : "haima_boss_10",
		scale : 0.4,
		protime : 43200,
		probase : 1,
		chip : "i657",
		name : "fish_name_hm",
		description : "fish_desc_hm",
		treasureid : 106,
	},
];
module.exports = aquarium_petfish_cfg;