var skill_skill_fish_cfg =
[
	{
		id : 1,
		skill_sound : "skill_5",
		skill_range : 3000,
		skill_immune : [2,3,5],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 1,
		value1 : "0",
		value2 : "0",
	},
	{
		id : 2,
		skill_sound : "fd_baozha",
		skill_range : 200,
		skill_immune : [2,3,5],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 2,
		value1 : "0",
		value2 : "0",
	},
	{
		id : 3,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 5000,
		cd : 99999,
		readytime : 0,
		type : 3,
		value1 : "0",
		value2 : "0",
	},
	{
		id : 4,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "055_move",
		delay : 5,
		cd : 20,
		readytime : 2,
		type : 4,
		value1 : "5",
		value2 : "5",
	},
	{
		id : 5,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "hudun",
		value2 : "1",
	},
	{
		id : 6,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 99999,
		cd : 99999,
		readytime : 0,
		type : 6,
		value1 : ".8",
		value2 : "2",
	},
	{
		id : 7,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 7,
		value1 : ".8",
		value2 : "0",
	},
	{
		id : 8,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 8,
		value1 : "1",
		value2 : ".001",
	},
	{
		id : 9,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 9,
		value1 : "1",
		value2 : "0",
	},
	{
		id : 10,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 5,
		cd : 5,
		readytime : 0,
		type : 11,
		value1 : "shou",
		value2 : "0",
	},
	{
		id : 11,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "baozang",
		value2 : "1",
	},
	{
		id : 12,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "baozang",
		value2 : "1",
	},
	{
		id : 13,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "baozang",
		value2 : "1",
	},
	{
		id : 14,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "hudun",
		value2 : "2",
	},
	{
		id : 15,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "hudun",
		value2 : "4",
	},
	{
		id : 16,
		skill_sound : "0",
		skill_range : 0,
		skill_immune : [],
		effect : "0",
		delay : 0,
		cd : 99999,
		readytime : 0,
		type : 5,
		value1 : "baozang",
		value2 : "30",
	},
];
module.exports = skill_skill_fish_cfg;