var treasure_treasure_cfg =
[
	{
		id : 1,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_10",
		time : 0,
		dropid : "r2",
		dropcount : 5,
		share : 0,
	},
	{
		id : 10,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_11",
		time : 3600,
		dropid : "r1",
		dropcount : 4,
		share : 0,
	},
	{
		id : 11,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_12",
		time : 10800,
		dropid : "r2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 12,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_13",
		time : 21600,
		dropid : "r3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 13,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_14",
		time : 43200,
		dropid : "r4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 101,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "t001",
		dropcount : 3,
		share : 0,
	},
	{
		id : 102,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "t002",
		dropcount : 3,
		share : 0,
	},
	{
		id : 103,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "t003",
		dropcount : 3,
		share : 0,
	},
	{
		id : 104,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "t004",
		dropcount : 3,
		share : 1,
	},
	{
		id : 105,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "t005",
		dropcount : 3,
		share : 1,
	},
	{
		id : 106,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "t006",
		dropcount : 3,
		share : 1,
	},
	{
		id : 1001,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 5,
		share : 0,
	},
	{
		id : 1002,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 5,
		share : 0,
	},
	{
		id : 1003,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 5,
		share : 0,
	},
	{
		id : 1004,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 5,
		share : 0,
	},
	{
		id : 1005,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 5,
		share : 0,
	},
	{
		id : 1011,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 6,
		share : 0,
	},
	{
		id : 1012,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 6,
		share : 0,
	},
	{
		id : 1013,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 6,
		share : 0,
	},
	{
		id : 1014,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 6,
		share : 0,
	},
	{
		id : 1015,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 6,
		share : 0,
	},
	{
		id : 1021,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1022,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1023,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1024,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1025,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1031,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1032,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1033,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1034,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1035,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1041,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 1042,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 1043,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 1044,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 1045,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 1051,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1052,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1053,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1054,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1055,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1061,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1062,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1063,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1064,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1065,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1071,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1072,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1073,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1074,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1075,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1101,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1102,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1103,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1104,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1105,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1111,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1112,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1113,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1114,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1115,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1121,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1122,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1123,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1124,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1125,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1131,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1132,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1133,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1134,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1135,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1141,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1142,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1143,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1144,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1145,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1151,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1152,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1153,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1154,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1155,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 1161,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1162,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1163,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1164,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1165,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 1171,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1172,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1173,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1174,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1175,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 1201,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1202,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1203,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1204,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1205,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 1211,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 1212,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 1213,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 1214,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 1215,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 2001,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2002,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2003,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2004,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2005,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2011,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2012,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2013,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2014,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2015,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2021,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2022,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2023,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2024,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2025,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2031,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2032,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2033,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2034,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2035,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2041,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2042,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2043,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2044,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2045,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 5,
		share : 1,
	},
	{
		id : 2051,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2052,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2053,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2054,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2055,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2061,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2062,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2063,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2064,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2065,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2071,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2072,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2073,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2074,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2075,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2101,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2102,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2103,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2104,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2105,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2111,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2112,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2113,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2114,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2115,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2121,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2122,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2123,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2124,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2125,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2131,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2132,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2133,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2134,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2135,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2141,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2142,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2143,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2144,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2145,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2151,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2152,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2153,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2154,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2155,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 6,
		share : 1,
	},
	{
		id : 2161,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2162,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2163,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2164,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2165,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 7,
		share : 1,
	},
	{
		id : 2171,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2172,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2173,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2174,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2175,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 8,
		share : 1,
	},
	{
		id : 2201,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2202,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2203,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2204,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2205,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 9,
		share : 1,
	},
	{
		id : 2211,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 10,
		share : 1,
	},
	{
		id : 2212,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 10,
		share : 1,
	},
	{
		id : 2213,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 10,
		share : 1,
	},
	{
		id : 2214,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 10,
		share : 1,
	},
	{
		id : 2215,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_2",
		dropcount : 10,
		share : 1,
	},
	{
		id : 3001,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3002,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3003,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3004,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3005,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3011,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3012,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3013,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3014,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3015,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3021,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3022,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3023,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3024,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3025,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3031,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3032,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3033,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3034,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3035,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3041,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3042,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3043,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3044,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3045,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 5,
		share : 1,
	},
	{
		id : 3051,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3052,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3053,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3054,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3055,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3061,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3062,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3063,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3064,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3065,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3071,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3072,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3073,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3074,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3075,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3101,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3102,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3103,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3104,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3105,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3111,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3112,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3113,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3114,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3115,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3121,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3122,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3123,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3124,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3125,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3131,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3132,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3133,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3134,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3135,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3141,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3142,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3143,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3144,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3145,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3151,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3152,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3153,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3154,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3155,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 6,
		share : 1,
	},
	{
		id : 3161,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3162,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3163,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3164,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3165,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 7,
		share : 1,
	},
	{
		id : 3171,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3172,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3173,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3174,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3175,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 8,
		share : 1,
	},
	{
		id : 3201,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3202,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3203,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3204,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3205,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 9,
		share : 1,
	},
	{
		id : 3211,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 10,
		share : 1,
	},
	{
		id : 3212,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 10,
		share : 1,
	},
	{
		id : 3213,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 10,
		share : 1,
	},
	{
		id : 3214,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 10,
		share : 1,
	},
	{
		id : 3215,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_3",
		dropcount : 10,
		share : 1,
	},
	{
		id : 4001,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4002,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4003,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4004,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4005,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4011,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4012,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4013,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4014,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4015,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4021,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4022,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4023,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4024,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4025,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4031,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4032,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4033,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4034,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4035,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4041,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4042,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4043,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4044,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4045,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 5,
		share : 1,
	},
	{
		id : 4051,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4052,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4053,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4054,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4055,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4061,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4062,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4063,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4064,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4065,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4071,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4072,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4073,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4074,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4075,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4101,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4102,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4103,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4104,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4105,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4111,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4112,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4113,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4114,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4115,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4121,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4122,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4123,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4124,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4125,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4131,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4132,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4133,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4134,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4135,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4141,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4142,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4143,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4144,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4145,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4151,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4152,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4153,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4154,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4155,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 6,
		share : 1,
	},
	{
		id : 4161,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4162,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4163,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4164,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4165,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 7,
		share : 1,
	},
	{
		id : 4171,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4172,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4173,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4174,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4175,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 8,
		share : 1,
	},
	{
		id : 4201,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4202,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4203,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4204,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4205,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 9,
		share : 1,
	},
	{
		id : 4211,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 4212,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 4213,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 4214,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 4215,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_4",
		dropcount : 10,
		share : 1,
	},
	{
		id : 5001,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5002,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5003,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5004,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5005,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5011,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5012,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5013,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5014,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5015,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5021,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5022,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5023,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5024,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5025,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5031,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5032,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5033,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5034,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5035,
		pic : "0",
		name : "treasure_name_1",
		desc : "treasure_desc_1",
		time : 0,
		dropid : "god1_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5041,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5042,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5043,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5044,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5045,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 5,
		share : 1,
	},
	{
		id : 5051,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5052,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5053,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5054,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5055,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5061,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5062,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5063,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5064,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5065,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5071,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5072,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5073,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5074,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5075,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5101,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5102,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5103,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5104,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5105,
		pic : "1",
		name : "treasure_name_2",
		desc : "treasure_desc_2",
		time : 0,
		dropid : "god2_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5111,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5112,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5113,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5114,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5115,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5121,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5122,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5123,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5124,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5125,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5131,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5132,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5133,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5134,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5135,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5141,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5142,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5143,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5144,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5145,
		pic : "2",
		name : "treasure_name_3",
		desc : "treasure_desc_3",
		time : 0,
		dropid : "god3_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5151,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5152,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5153,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5154,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5155,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 6,
		share : 1,
	},
	{
		id : 5161,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5162,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5163,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5164,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5165,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 7,
		share : 1,
	},
	{
		id : 5171,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5172,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5173,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5174,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5175,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 8,
		share : 1,
	},
	{
		id : 5201,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5202,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5203,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5204,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5205,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 9,
		share : 1,
	},
	{
		id : 5211,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 10,
		share : 1,
	},
	{
		id : 5212,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 10,
		share : 1,
	},
	{
		id : 5213,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 10,
		share : 1,
	},
	{
		id : 5214,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 10,
		share : 1,
	},
	{
		id : 5215,
		pic : "3",
		name : "treasure_name_4",
		desc : "treasure_desc_4",
		time : 0,
		dropid : "god4_5",
		dropcount : 10,
		share : 1,
	},
];
module.exports = treasure_treasure_cfg;