module.exports ={
   ID:'id',
   UID:'uid',
   PERIOD:'period',
   IDENTIFY:'identify',
   BETDATA:'betData',
   BETTYPEINFO:'betTypeInfo',
   BETITEMS:'betItems',
   BETCOUNT:'betCount',
   BETMONEY:'betMoney',
   WINCOUNT:'winCount',
   WINMONEY:'winMoney',
   BETTIME:'betTime',
   STATE:'state',
};