var daily_dailypast_cfg =
[
	{
		id : 1,
		type : 1,
		reward : ["i001",5000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 2,
		type : 1,
		reward : ["i400",1],
		label : "yqdgrounding_3",
		description : "dailypast_desc_2",
		viplevel : 1,
	},
	{
		id : 3,
		type : 1,
		reward : ["i501",10],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 4,
		type : 1,
		reward : ["i002",5],
		label : "yqdgrounding_3",
		description : "dailypast_desc_4",
		viplevel : 2,
	},
	{
		id : 5,
		type : 1,
		reward : ["i004",1],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 6,
		type : 1,
		reward : ["i015",1],
		label : "yqdgrounding_2",
		description : "dailypast_desc_6",
		viplevel : -1,
	},
	{
		id : 7,
		type : 1,
		reward : ["i001",10000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 8,
		type : 1,
		reward : ["i400",2],
		label : "yqdgrounding_3",
		description : "dailypast_desc_8",
		viplevel : 3,
	},
	{
		id : 9,
		type : 1,
		reward : ["i502",10],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 10,
		type : 1,
		reward : ["i002",10],
		label : "yqdgrounding_3",
		description : "dailypast_desc_10",
		viplevel : 4,
	},
	{
		id : 11,
		type : 1,
		reward : ["i004",2],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 12,
		type : 1,
		reward : ["i015",1],
		label : "yqdgrounding_4",
		description : "dailypast_desc_6",
		viplevel : -1,
	},
	{
		id : 13,
		type : 1,
		reward : ["i001",15000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 14,
		type : 1,
		reward : ["i400",3],
		label : "yqdgrounding_3",
		description : "dailypast_desc_14",
		viplevel : 5,
	},
	{
		id : 15,
		type : 1,
		reward : ["i503",10],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 16,
		type : 1,
		reward : ["i002",15],
		label : "yqdgrounding_3",
		description : "dailypast_desc_16",
		viplevel : 6,
	},
	{
		id : 17,
		type : 1,
		reward : ["i004",3],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 18,
		type : 1,
		reward : ["i015",1],
		label : "yqdgrounding_4",
		description : "dailypast_desc_6",
		viplevel : -1,
	},
	{
		id : 19,
		type : 1,
		reward : ["i001",20000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 20,
		type : 1,
		reward : ["i400",4],
		label : "yqdgrounding_3",
		description : "dailypast_desc_20",
		viplevel : 7,
	},
	{
		id : 21,
		type : 1,
		reward : ["i504",10],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 22,
		type : 1,
		reward : ["i002",20],
		label : "yqdgrounding_3",
		description : "dailypast_desc_22",
		viplevel : 8,
	},
	{
		id : 23,
		type : 1,
		reward : ["i004",4],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 24,
		type : 1,
		reward : ["i015",1],
		label : "yqdgrounding_4",
		description : "dailypast_desc_6",
		viplevel : -1,
	},
	{
		id : 25,
		type : 1,
		reward : ["i001",25000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 26,
		type : 1,
		reward : ["i400",5],
		label : "yqdgrounding_3",
		description : "dailypast_desc_26",
		viplevel : 9,
	},
	{
		id : 27,
		type : 1,
		reward : ["i505",10],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 28,
		type : 1,
		reward : ["i002",25],
		label : "yqdgrounding_3",
		description : "dailypast_desc_28",
		viplevel : 10,
	},
	{
		id : 29,
		type : 1,
		reward : ["i004",5],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 30,
		type : 1,
		reward : ["i015",1],
		label : "yqdgrounding_2",
		description : "dailypast_desc_6",
		viplevel : -1,
	},
	{
		id : 31,
		type : 1,
		reward : ["i001",50000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 1,
		type : 0,
		reward : ["i001",500],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 2,
		type : 0,
		reward : ["i012",5],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 3,
		type : 0,
		reward : ["i001",4000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 4,
		type : 0,
		reward : ["i011",5],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 5,
		type : 0,
		reward : ["i001",20000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 6,
		type : 0,
		reward : ["i002",20],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 7,
		type : 0,
		reward : ["i001",50000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 901,
		type : 2,
		reward : ["i001",3000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 902,
		type : 2,
		reward : ["i001",3500],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 903,
		type : 2,
		reward : ["i001",4000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 904,
		type : 2,
		reward : ["i001",4500],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 905,
		type : 2,
		reward : ["i001",5000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 906,
		type : 2,
		reward : ["i001",25000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 907,
		type : 2,
		reward : ["i001",30000],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 910,
		type : 2,
		reward : [["i002",10],["i001",1000],["i015",1]],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
	{
		id : 911,
		type : 2,
		reward : [["i001",10000],["i002",5],["i400",1]],
		label : "0",
		description : "dailypast_desc_0",
		viplevel : -1,
	},
];
module.exports = daily_dailypast_cfg;