var daily_pirate_cfg =
[
	{
		ID : 1,
		condition1 : ["dabaisha",2],
		condition2 : ["shuimu",10],
		probability : 100,
		reward : "pirate1",
	},
	{
		ID : 2,
		condition1 : ["haitun",5],
		condition2 : ["xiaochouyu_huang",20],
		probability : 100,
		reward : "pirate2",
	},
	{
		ID : 3,
		condition1 : ["shuimu_jj",2],
		condition2 : ["jianyu",10],
		probability : 80,
		reward : "pirate3",
	},
	{
		ID : 4,
		condition1 : ["shuangshengyu_jj",2],
		condition2 : ["haigui",10],
		probability : 100,
		reward : "pirate4",
	},
	{
		ID : 5,
		condition1 : ["dabaisha",2],
		condition2 : ["xiaochouyu_huang",20],
		probability : 80,
		reward : "pirate5",
	},
	{
		ID : 6,
		condition1 : ["sanshengyu_jj",2],
		condition2 : ["haitun",5],
		probability : 100,
		reward : "pirate6",
	},
	{
		ID : 7,
		condition1 : ["sanshengyu_jj",2],
		condition2 : ["dabaisha",2],
		probability : 100,
		reward : "pirate7",
	},
	{
		ID : 8,
		condition1 : ["xiaochouyu_huang",20],
		condition2 : ["shuangshengyu_jj",2],
		probability : 100,
		reward : "pirate8",
	},
	{
		ID : 9,
		condition1 : ["shuimu",10],
		condition2 : ["moguiyu_lan",2],
		probability : 100,
		reward : "pirate9",
	},
	{
		ID : 10,
		condition1 : ["moguiyu_lan",2],
		condition2 : ["haitun",5],
		probability : 100,
		reward : "pirate10",
	},
	{
		ID : 11,
		condition1 : ["haitun_jj",5],
		condition2 : ["feicuiyu",80],
		probability : 100,
		reward : "pirate11",
	},
	{
		ID : 12,
		condition1 : ["moguiyu_lan",5],
		condition2 : ["diaoyu",40],
		probability : 100,
		reward : "pirate12",
	},
	{
		ID : 13,
		condition1 : ["chuitousha",5],
		condition2 : ["feicuiyu",80],
		probability : 100,
		reward : "pirate13",
	},
	{
		ID : 14,
		condition1 : ["dabaisha",5],
		condition2 : ["hetun_huang",50],
		probability : 100,
		reward : "pirate14",
	},
	{
		ID : 15,
		condition1 : ["dinianyu_zi",20],
		condition2 : ["dianman",1],
		probability : 100,
		reward : "pirate15",
	},
	{
		ID : 16,
		condition1 : ["haima_boss",1],
		condition2 : ["jiaodie_lan",50],
		probability : 100,
		reward : "pirate16",
	},
	{
		ID : 21,
		condition1 : ["hujing",10],
		condition2 : ["shuimu_lan",50],
		probability : 100,
		reward : "pirate21",
	},
	{
		ID : 22,
		condition1 : ["moguiyu_hong",10],
		condition2 : ["baoshiyu_zi",100],
		probability : 100,
		reward : "pirate22",
	},
	{
		ID : 23,
		condition1 : ["haitun",10],
		condition2 : ["duanhuibiyu_huang",100],
		probability : 100,
		reward : "pirate23",
	},
	{
		ID : 24,
		condition1 : ["dabaisha",10],
		condition2 : ["xiaochouyu_lan",180],
		probability : 100,
		reward : "pirate24",
	},
	{
		ID : 25,
		condition1 : ["moguiyu_jj",5],
		condition2 : ["hetun_lan",80],
		probability : 100,
		reward : "pirate25",
	},
	{
		ID : 26,
		condition1 : ["zhangyu_boss",1],
		condition2 : ["caomeiyu",130],
		probability : 100,
		reward : "pirate26",
	},
	{
		ID : 31,
		condition1 : ["hujing",10],
		condition2 : ["jinqiangyu",130],
		probability : 100,
		reward : "pirate11",
	},
	{
		ID : 32,
		condition1 : ["moguiyu_lan",10],
		condition2 : ["jianyu",70],
		probability : 100,
		reward : "pirate12",
	},
	{
		ID : 33,
		condition1 : ["chuitousha",10],
		condition2 : ["shuijingyu",130],
		probability : 100,
		reward : "pirate13",
	},
	{
		ID : 34,
		condition1 : ["baozhay",10],
		condition2 : ["hetun_huang",80],
		probability : 100,
		reward : "pirate14",
	},
	{
		ID : 35,
		condition1 : ["cheqiyu_jj",20],
		condition2 : ["dinianyu_lan",70],
		probability : 100,
		reward : "pirate15",
	},
	{
		ID : 36,
		condition1 : ["longgui_boss",1],
		condition2 : ["jiaodie_lan",80],
		probability : 100,
		reward : "pirate16",
	},
	{
		ID : 100,
		condition1 : ["cheqiyu_jj_9",1],
		condition2 : ["hetun_lan_9",5],
		probability : 100,
		reward : "pirate25",
	},
	{
		ID : 101,
		condition1 : ["haitun_jj_9",1],
		condition2 : ["shuijingyu_9",5],
		probability : 100,
		reward : "pirate26",
	},
];
module.exports = daily_pirate_cfg;