var scene_tide_cfg =
[
	{
		id : 1001,
		name : "捕捞季",
		during : 70,
		type : 0,
		tide_file : "bulaoji_yc.json",
		pic : "bulaoji",
		bgm : "bgm_tide",
		sound : "tide_1001",
		time : 5,
	},
	{
		id : 1002,
		name : "引擎轰鸣",
		during : 65,
		type : 0,
		tide_file : "car_yc.json",
		pic : "yinqing",
		bgm : "bgm_tide",
		sound : "tide_1002",
		time : 5,
	},
	{
		id : 1003,
		name : "怪兽脚印",
		during : 65,
		type : 0,
		tide_file : "footmark_yc.json",
		pic : "jiaoying",
		bgm : "bgm_tide",
		sound : "tide_1003",
		time : 5,
	},
	{
		id : 1004,
		name : "象群来去",
		during : 63,
		type : 0,
		tide_file : "elephant_yc.json",
		pic : "xiangqun",
		bgm : "bgm_tide",
		sound : "tide_1004",
		time : 5,
	},
	{
		id : 1005,
		name : "蝴蝶",
		during : 63,
		type : 0,
		tide_file : "hudie_yc.json",
		pic : "hudie",
		bgm : "bgm_tide",
		sound : "tide_1005",
		time : 5,
	},
	{
		id : 1006,
		name : "鱼阵",
		during : 63,
		type : 0,
		tide_file : "fish_yc.json",
		pic : "xianyu",
		bgm : "bgm_tide",
		sound : "tide_1006",
		time : 5,
	},
];
module.exports = scene_tide_cfg;